// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

//app/layout.js
import { Providers } from "./providers";
import "./globals.css";

export const metadata = {
  title: "VM3 CMS",
  description: "Admin Panel",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}


// "use client";

// import { Sidebar } from "@/components/dashboard/Sidebar";
// import { Topbar } from "@/components/dashboard/Topbar";
// import { useAppSelector } from "@/redux/hooks";
// import { useRouter } from "next/navigation";
// import { useEffect } from "react";

// export default function AdminLayout({ children }) {
//   const isAuthenticated = useAppSelector((state) => state.auth.isAuthenticated);
//   const router = useRouter();

//   useEffect(() => {
//     if (!isAuthenticated) {
//       router.push("/admin/login");
//     }
//   }, [isAuthenticated]);

//   if (!isAuthenticated) return null;

//   return (
//     <div className="flex bg-gray-50 min-h-screen">
//       <Sidebar />

//       <div className="flex-1 flex flex-col">
//         <Topbar />

//         <main className="flex-1 p-10">
//           {children}
//         </main>
//       </div>
//     </div>
//   );
// }
